# Generated by Django 5.0.4 on 2024-05-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
