# Generated by Django 5.0.4 on 2024-05-20 21:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_usuario_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiche',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publica',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
