# Generated by Django 5.0.4 on 2024-06-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_alter_afiche_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiche',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
