# Generated by Django 5.0.4 on 2024-07-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_alter_afiche_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='precio',
        ),
        migrations.AddField(
            model_name='afiche',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
